/**
 * Auth tables, owned by Better Auth.
 *
 * Better Auth requires this exact table and column shape (camelCase field names
 * mapped to snake_case columns). The password hash lives in `account.password`,
 * not on the user row — Better Auth stores credentials as an "account" with
 * providerId 'credential', the same slot an OAuth provider would occupy.
 *
 * `role` and `active` are our additions, declared to Better Auth as
 * additionalFields in lib/auth.ts so they round-trip through the session.
 *
 * Every user foreign key in the rest of the schema — created_by,
 * mentor_user_id, recorded_by_user_id, actor_user_id — points at `user.id`.
 * Ids are UUID v7, generated by lib/ids.ts and handed to Better Auth via its
 * `advanced.database.generateId` hook.
 */

import { boolean, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core"

import { userRoleEnum } from "./enums"

export const users = pgTable("user", {
  id: uuid("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),

  // --- ShubzTrader additions ---
  role: userRoleEnum("role").notNull().default("OPERATOR"),
  active: boolean("active").notNull().default(true),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

/**
 * Named `authSessions`, not `sessions`: the catalogue has class sessions, and
 * two exports of the same name would collide in schema/index.ts — silently, as
 * an ambiguous star export, which is how the class sessions table went missing
 * from the first generated migration.
 */
export const authSessions = pgTable("session", {
  id: uuid("id").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  token: text("token").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const accounts = pgTable("account", {
  id: uuid("id").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  issuer: text("issuer").notNull().default("local:credential"),
  /** scrypt hash for providerId 'credential'. Never read this directly. */
  password: text("password"),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
  scope: text("scope"),
  idToken: text("id_token"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const verifications = pgTable("verification", {
  id: uuid("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export type User = typeof users.$inferSelect
export type UserRole = User["role"]
