/**
 * Messaging — SCHEMA ONLY IN THIS PASS.
 *
 * No logic is built here yet and no Meta API call is made. These tables exist
 * now purely so that connecting WhatsApp later requires no migration against a
 * live production database.
 *
 * Two shapes are worth reading before extending this:
 *
 * 1. `messages` is ONE table for inbound AND outbound, discriminated by
 *    `direction`. Not two tables. A conversation is a single ordered stream;
 *    splitting it would make "show me this contact's thread" a UNION and make
 *    the 24-hour service window (which depends on the last INBOUND message)
 *    awkward to compute.
 *
 * 2. Sends are idempotent by construction. `idempotency_key` is generated by
 *    the client BEFORE the send and is UNIQUE, so a retried request cannot
 *    produce a second WhatsApp message. `wamid` is Meta's id, unique and
 *    nullable because it only exists once Meta has accepted the message.
 */

import { relations } from "drizzle-orm"
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core"

import { users } from "./auth"
import { batches, programs } from "./catalogue"
import { contacts } from "./contacts"
import {
  campaignStatusEnum,
  messageChannelEnum,
  messageDirectionEnum,
  messageStatusEnum,
  scheduledJobStatusEnum,
  templateCategoryEnum,
  templateStatusEnum,
} from "./enums"

export const messageTemplates = pgTable(
  "message_templates",
  {
    id: uuid("id").primaryKey(),
    /** What we call it internally, e.g. "session_reminder_24h". */
    internalName: text("internal_name").notNull().unique(),
    /** The name registered with Meta, which has its own naming rules. */
    metaTemplateName: text("meta_template_name"),
    language: text("language").notNull().default("en"),

    category: templateCategoryEnum("category").notNull().default("UTILITY"),
    status: templateStatusEnum("status").notNull().default("DRAFT"),

    bodyText: text("body_text"),
    components: jsonb("components"),
    /**
     * Maps Meta's positional parameters to friendly field names, e.g.
     * {"1":"first_name","2":"session_time","3":"meeting_link"}.
     * Meta templates take {{1}}, {{2}}...; this is how we know what to put there.
     */
    variableMap: jsonb("variable_map"),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("message_templates_status_idx").on(t.status)]
)

export const campaigns = pgTable(
  "campaigns",
  {
    id: uuid("id").primaryKey(),
    name: text("name").notNull(),
    programId: uuid("program_id").references(() => programs.id, {
      onDelete: "set null",
    }),
    batchId: uuid("batch_id").references(() => batches.id, { onDelete: "set null" }),
    templateId: uuid("template_id").references(() => messageTemplates.id, {
      onDelete: "restrict",
    }),

    /** The saved query that defined the audience, for reference after the fact. */
    audienceFilter: jsonb("audience_filter"),

    status: campaignStatusEnum("status").notNull().default("DRAFT"),

    scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),

    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("campaigns_status_idx").on(t.status),
    index("campaigns_scheduled_at_idx").on(t.scheduledAt),
  ]
)

/**
 * The audience, FROZEN at confirm time.
 *
 * Snapshotting matters: if the audience were re-evaluated at send time, a
 * campaign confirmed against 400 people could go out to 450 because someone
 * imported a CSV in between. `resolved_variables` freezes each recipient's
 * merge values too, so the message that was previewed is the message that sends.
 */
export const campaignRecipients = pgTable(
  "campaign_recipients",
  {
    id: uuid("id").primaryKey(),
    campaignId: uuid("campaign_id")
      .notNull()
      .references(() => campaigns.id, { onDelete: "cascade" }),
    contactId: uuid("contact_id")
      .notNull()
      .references(() => contacts.id, { onDelete: "cascade" }),
    resolvedVariables: jsonb("resolved_variables"),
    /** Set when a snapshotted recipient is skipped: opted out, no consent, invalid number. */
    excludedReason: text("excluded_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("campaign_recipients_campaign_id_idx").on(t.campaignId),
    index("campaign_recipients_contact_id_idx").on(t.contactId),
  ]
)

export const messages = pgTable(
  "messages",
  {
    id: uuid("id").primaryKey(),
    contactId: uuid("contact_id")
      .notNull()
      .references(() => contacts.id, { onDelete: "cascade" }),
    campaignId: uuid("campaign_id").references(() => campaigns.id, {
      onDelete: "set null",
    }),
    templateId: uuid("template_id").references(() => messageTemplates.id, {
      onDelete: "set null",
    }),

    direction: messageDirectionEnum("direction").notNull(),
    channel: messageChannelEnum("channel").notNull().default("WHATSAPP"),

    /** Client-generated before the send. UNIQUE — this is what makes retries safe. */
    idempotencyKey: text("idempotency_key").notNull().unique(),
    /** Meta's message id. Null until Meta accepts; unique thereafter. */
    wamid: text("wamid").unique(),

    bodyText: text("body_text"),
    payload: jsonb("payload"),

    status: messageStatusEnum("status").notNull().default("PENDING"),
    errorCode: text("error_code"),
    errorMessage: text("error_message"),

    queuedAt: timestamp("queued_at", { withTimezone: true }),
    sentAt: timestamp("sent_at", { withTimezone: true }),
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    readAt: timestamp("read_at", { withTimezone: true }),
    failedAt: timestamp("failed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Backs the conversation thread on a contact.
    index("messages_contact_created_idx").on(t.contactId, t.createdAt),
    index("messages_campaign_id_idx").on(t.campaignId),
    index("messages_status_idx").on(t.status),
    index("messages_direction_idx").on(t.direction),
  ]
)

/** Status callbacks from the provider: sent -> delivered -> read, or failed. */
export const messageEvents = pgTable(
  "message_events",
  {
    id: uuid("id").primaryKey(),
    messageId: uuid("message_id")
      .notNull()
      .references(() => messages.id, { onDelete: "cascade" }),
    eventType: text("event_type").notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
    raw: jsonb("raw"),
  },
  (t) => [index("message_events_message_id_idx").on(t.messageId, t.occurredAt)]
)

/**
 * Raw provider webhooks, stored before interpretation.
 *
 * `signature_valid` is recorded rather than enforced at the door so that
 * forged or misconfigured calls leave evidence instead of vanishing.
 */
export const webhookEvents = pgTable(
  "webhook_events",
  {
    id: uuid("id").primaryKey(),
    provider: text("provider").notNull(),
    signatureValid: boolean("signature_valid").notNull().default(false),
    raw: jsonb("raw").notNull(),
    receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
    processedAt: timestamp("processed_at", { withTimezone: true }),
    error: text("error"),
  },
  (t) => [
    index("webhook_events_provider_idx").on(t.provider, t.receivedAt),
    index("webhook_events_processed_at_idx").on(t.processedAt),
  ]
)

/** Deferred work: send this campaign at 9am, retry that failed message. */
export const scheduledJobs = pgTable(
  "scheduled_jobs",
  {
    id: uuid("id").primaryKey(),
    jobType: text("job_type").notNull(),
    runAt: timestamp("run_at", { withTimezone: true }).notNull(),
    payload: jsonb("payload"),
    status: scheduledJobStatusEnum("status").notNull().default("PENDING"),
    attempts: integer("attempts").notNull().default(0),
    lastError: text("last_error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // The claim query: pending jobs whose time has come.
    index("scheduled_jobs_status_run_at_idx").on(t.status, t.runAt),
  ]
)

export const campaignsRelations = relations(campaigns, ({ one, many }) => ({
  program: one(programs, {
    fields: [campaigns.programId],
    references: [programs.id],
  }),
  batch: one(batches, { fields: [campaigns.batchId], references: [batches.id] }),
  template: one(messageTemplates, {
    fields: [campaigns.templateId],
    references: [messageTemplates.id],
  }),
  recipients: many(campaignRecipients),
  messages: many(messages),
}))

export const campaignRecipientsRelations = relations(campaignRecipients, ({ one }) => ({
  campaign: one(campaigns, {
    fields: [campaignRecipients.campaignId],
    references: [campaigns.id],
  }),
  contact: one(contacts, {
    fields: [campaignRecipients.contactId],
    references: [contacts.id],
  }),
}))

export const messagesRelations = relations(messages, ({ one, many }) => ({
  contact: one(contacts, {
    fields: [messages.contactId],
    references: [contacts.id],
  }),
  campaign: one(campaigns, {
    fields: [messages.campaignId],
    references: [campaigns.id],
  }),
  template: one(messageTemplates, {
    fields: [messages.templateId],
    references: [messageTemplates.id],
  }),
  events: many(messageEvents),
}))

export const messageEventsRelations = relations(messageEvents, ({ one }) => ({
  message: one(messages, {
    fields: [messageEvents.messageId],
    references: [messages.id],
  }),
}))

export const messageTemplatesRelations = relations(messageTemplates, ({ many }) => ({
  campaigns: many(campaigns),
  messages: many(messages),
}))

export type MessageTemplate = typeof messageTemplates.$inferSelect
export type Campaign = typeof campaigns.$inferSelect
export type Message = typeof messages.$inferSelect
export type NewMessage = typeof messages.$inferInsert
