/**
 * The messaging provider interface — SCAFFOLD ONLY IN THIS PASS.
 *
 * No implementation calls Meta yet. This exists so the shape of the seam is
 * fixed now: when WhatsApp is connected, a WhatsAppProvider implements this
 * and the rest of the application is unchanged.
 *
 * Two decisions are encoded in these signatures and worth keeping:
 *
 *   1. `sendTemplate` takes an `idempotencyKey` from the CALLER, generated
 *      before the send. It is the unique key on the messages table, so a
 *      retried request — a timeout, a double-click, a queue redelivery —
 *      cannot produce a second WhatsApp message to a real person.
 *
 *   2. `handleWebhook` receives the raw body and signature rather than parsed
 *      JSON, because the signature must be verified against the exact bytes
 *      received. Parsing first and re-serialising changes them.
 */

import type { MessageStatus } from "@/db/schema"

export type TemplateVariables = Record<string, string>

export type SendTemplateInput = {
  /** Canonical E.164, as stored on the contact. */
  toPhoneE164: string
  contactId: string
  /** The template's registered name, not our internal one. */
  templateName: string
  language: string
  /** Resolved at confirm time and frozen, so preview matches what is sent. */
  variables: TemplateVariables
  /** Generated by the caller BEFORE sending. Unique; makes retries safe. */
  idempotencyKey: string
  campaignId?: string | null
  templateId?: string | null
}

export type SendTemplateResult =
  | { ok: true; messageId: string; wamid: string | null; status: MessageStatus }
  | { ok: false; messageId: string | null; errorCode: string; errorMessage: string }

export type MessageStatusResult = {
  status: MessageStatus
  wamid: string | null
  deliveredAt: Date | null
  readAt: Date | null
  errorCode: string | null
  errorMessage: string | null
}

export type WebhookResult = {
  /** False when the signature did not verify — recorded, not thrown away. */
  signatureValid: boolean
  /** How many status updates or inbound messages were applied. */
  processed: number
  error?: string
}

export interface MessagingProvider {
  readonly name: string

  sendTemplate(input: SendTemplateInput): Promise<SendTemplateResult>

  getStatus(messageId: string): Promise<MessageStatusResult | null>

  /**
   * @param rawBody the exact bytes received; the signature is computed over these
   * @param signature the provider's signature header
   */
  handleWebhook(rawBody: string, signature: string | null): Promise<WebhookResult>
}
